modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/LGatodu47/ScreenshotViewer/issues"

[[mods]]
modId="screenshot_viewer"
version="${file.jarVersion}"
displayName="Screenshot Viewer"
logoFile="icon.png"
authors="LGatodu47"
credits="Ocelot5836 for screenshot lazy loading, Wudji for zn_cn lang"
displayTest="IGNORE_ALL_VERSION"
description="A mod that allows you to see and manage your screenshots in game!"

[[dependencies.screenshot_viewer]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.screenshot_viewer]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="CLIENT"
